In [ ]:
import numpy as np
import kaiwu as kw

# Import the plotting library
import matplotlib.pyplot as plt


2025-01-15 14:25:29,694 - matplotlib - _get_config_or_cache_dir - 531 - WARNING - Matplotlib created a temporary cache directory at /var/folders/zn/4tn977cn5d75zhj54g4zg_br0000gn/T/matplotlib-oy0cyjc8 because the default path (/Users/abel-sun/.matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [ ]:
# invert input graph matrix
matrix = -np.array([
                [0, 1, 0, 1, 1, 0, 0, 1, 1, 0],
                [1, 0, 1, 0, 0, 1, 1, 1, 0, 0],
                [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
                [1, 0, 1, 0, 0, 1, 1, 0 ,1, 0],
                [1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
                [0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
                [0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
                [1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
                [1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
                [0, 0, 0, 0, 1, 1, 1, 0, 1, 0]])
                
worker = kw.classical.SimulatedAnnealingOptimizer(initial_temperature=100,
                                                  alpha=0.99,
                                                  cutoff_temperature=0.001,
                                                  iterations_per_t=10,
                                                  size_limit=100)
output = worker.solve(matrix)
opt = kw.sampler.optimal_sampler(matrix, output, 0)
best = opt[0][0]
max_cut = (np.sum(-matrix)-np.dot(-matrix,best).dot(best))/4
print("The obtained max cut is " + str(max_cut) + ".")

[[-1 -1  1 -1 -1  1  1 -1  1 -1]
 [-1 -1  1 -1 -1  1  1  1  1  1]
 [-1 -1  1  1  1 -1 -1  1 -1  1]
 [-1 -1  1 -1  1 -1  1 -1  1 -1]
 [-1 -1  1  1 -1  1 -1  1 -1 -1]
 [-1 -1  1  1  1  1  1  1 -1 -1]
 [-1  1  1  1 -1 -1 -1 -1  1  1]
 [-1 -1  1 -1  1 -1  1  1  1 -1]
 [-1 -1  1  1 -1 -1  1  1 -1  1]
 [-1  1 -1  1  1  1 -1  1  1 -1]
 [-1  1  1 -1  1  1  1 -1  1 -1]
 [-1  1 -1 -1  1 -1 -1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1 -1  1 -1]
 [ 1 -1 -1  1 -1  1  1  1 -1  1]
 [ 1 -1  1  1 -1  1  1 -1 -1 -1]
 [ 1 -1  1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1 -1  1  1 -1 -1]
 [-1  1  1 -1 -1  1 -1  1 -1  1]
 [ 1 -1 -1 -1 -1  1 -1  1 -1  1]
 [ 1  1 -1  1 -1  1 -1  1 -1  1]
 [ 1 -1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1 -1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1  1  1]
 [-1  1 -1  1 -1 -1 -1 -1 -1  1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1 -1  1  1 -1  1 -1 -1 -1  1]
 [ 1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1 -1  1 -1 -1 -1  1  1  1 -1]
 [ 1  1  1  1 -1  1 -1 -1 -1  1]
 [ 1 -1  1

AttributeError: module 'kaiwu' has no attribute 'qubo'

NameError: name 'result' is not defined