In [1]:
# 第一个代码块：导入必要的库
import kaiwu as kw
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


2025-01-15 14:25:29,694 - matplotlib - _get_config_or_cache_dir - 531 - WARNING - Matplotlib created a temporary cache directory at /var/folders/zn/4tn977cn5d75zhj54g4zg_br0000gn/T/matplotlib-oy0cyjc8 because the default path (/Users/abel-sun/.matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [2]:
matrix = -np.array([
                [0, 1, 0, 1, 1, 0, 0, 1, 1, 0],
                [1, 0, 1, 0, 0, 1, 1, 1, 0, 0],
                [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
                [1, 0, 1, 0, 0, 1, 1, 0 ,1, 0],
                [1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
                [0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
                [0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
                [1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
                [1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
                [0, 0, 0, 0, 1, 1, 1, 0, 1, 0]])
    
worker = kw.classical.SimulatedAnnealingOptimizer(initial_temperature=100,
                                                  alpha=0.99,
                                                  cutoff_temperature=0.001,
                                                  iterations_per_t=10,
                                                  size_limit=100)
output = worker.solve(matrix)
print(output)
opt = kw.sampler.optimal_sampler(matrix, output, 0)
best = opt[0][0]
max_cut = (np.sum(-matrix)-np.dot(-matrix,best).dot(best))/4
print("The obtained max cut is "+str(max_cut)+".")

[[-1 -1  1 -1 -1  1  1 -1  1 -1]
 [-1 -1  1 -1 -1  1  1  1  1  1]
 [-1 -1  1  1  1 -1 -1  1 -1  1]
 [-1 -1  1 -1  1 -1  1 -1  1 -1]
 [-1 -1  1  1 -1  1 -1  1 -1 -1]
 [-1 -1  1  1  1  1  1  1 -1 -1]
 [-1  1  1  1 -1 -1 -1 -1  1  1]
 [-1 -1  1 -1  1 -1  1  1  1 -1]
 [-1 -1  1  1 -1 -1  1  1 -1  1]
 [-1  1 -1  1  1  1 -1  1  1 -1]
 [-1  1  1 -1  1  1  1 -1  1 -1]
 [-1  1 -1 -1  1 -1 -1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1 -1  1 -1]
 [ 1 -1 -1  1 -1  1  1  1 -1  1]
 [ 1 -1  1  1 -1  1  1 -1 -1 -1]
 [ 1 -1  1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1 -1  1  1 -1 -1]
 [-1  1  1 -1 -1  1 -1  1 -1  1]
 [ 1 -1 -1 -1 -1  1 -1  1 -1  1]
 [ 1  1 -1  1 -1  1 -1  1 -1  1]
 [ 1 -1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1 -1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1  1  1]
 [-1  1 -1  1 -1 -1 -1 -1 -1  1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1 -1  1  1 -1  1 -1 -1 -1  1]
 [ 1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1 -1  1 -1 -1 -1  1  1  1 -1]
 [ 1  1  1  1 -1  1 -1 -1 -1  1]
 [ 1 -1  1

In [3]:
# 第三个代码块：构建QUBO模型
n = w.shape[0]

# 创建QUBO变量
x = kw.qubo.array(n, "x", kw.qubo.Binary)

# 创建QUBO模型
model = kw.qubo.QuboModel()

# 设置目标函数
objective = kw.qubo.quicksum([
    w[i,j] * x[i] * (1 - x[j])
    for i in range(n)
    for j in range(i+1, n)
])

model.set_objective(objective)

# 获取QUBO矩阵
qubo_mat = model.get_qubo_matrix()
print("最大割问题的QUBO矩阵:")
print(pd.DataFrame(qubo_mat))

AttributeError: module 'kaiwu' has no attribute 'qubo'

In [ ]:
# 第四个代码块：求解QUBO问题
# 使用模拟退火求解器
solver = kw.solver.LocalSimulatedAnnealingSolver()
result = solver.solve(model)

print("求解结果:")
print(result.solutions)

In [1]:
# 第五个代码块：可视化结果
# 获取最优解
solution = result.solutions[0]

# 创建两个顶点集合
set1 = [i for i, val in enumerate(solution) if val == 1]
set2 = [i for i, val in enumerate(solution) if val == 0]

# 可视化分割结果
plt.figure(figsize=(8, 6))
pos = nx.spring_layout(G)
# 绘制第一组节点
nx.draw_networkx_nodes(G, pos, nodelist=set1, node_color='lightblue', 
                      node_size=500)
# 绘制第二组节点
nx.draw_networkx_nodes(G, pos, nodelist=set2, node_color='lightgreen', 
                      node_size=500)
# 绘制边
nx.draw_networkx_edges(G, pos)
# 添加节点标签
nx.draw_networkx_labels(G, pos, font_size=16, font_weight='bold')

plt.title("最大割结果可视化\n蓝色和绿色表示不同的顶点集合")
plt.show()

# 计算最大割的值
cut_value = sum(w[i,j] for i in set1 for j in set2)
print(f"最大割的值: {cut_value}")

NameError: name 'result' is not defined